# Generated by Django 4.0.4 on 2022-05-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
